const specialitiesOptions = [
  "Primary Care Physician (PCP)",
  "OB-GYN (Obstetrician-Gynecologist)",
  "Dermatologist",
  "Dentist",
  "Ear, Nose & Throat Doctor (ENT / Otolaryngologist)",
  "Eye Doctor",
  "Psychiatrist",
  "Orthopedic Surgeon (Orthopedist)",
  "Acupuncturist",
  "Allergist (Immunologist)",
  "Audiologist",
  "Cardiologist (Heart Doctor)",
  "Cardiothoracic Surgeon",
  "Chiropractor",
  "Colorectal Surgeon",
  "Dentist",
  "Dermatologist",
  "Dietitian / Nutritionist",
  "Ear, Nose & Throat Doctor (ENT / Otolaryngologist)",
  "Endocrinologist (incl Diabetes Specialists)",
  "Eye Doctor",
  "Gastroenterologist",
  "Geriatrician",
  "Hearing Specialist",
  "Hematologist (Blood Specialist)",
  "Infectious Disease Specialist",
  "Infertility Specialist",
  "Midwife",
  "Naturopathic Doctor",
  "Nephrologist (Kidney Specialist)",
  "Neurologist (incl Headache Specialists)",
  "Neurosurgeon",
  "OB-GYN (Obstetrician-Gynecologist)",
  "Oncologist",
  "Ophthalmologist",
  "Optometrist",
  "Oral Surgeon",
  "Orthodontist",
  "Orthopedic Surgeon (Orthopedist)",
  "Pain Management Specialist",
  "Pediatric Dentist",
  "Pediatrician",
  "Physiatrist (Physical Medicine)",
  "Physical Therapist",
  "Plastic Surgeon",
  "Podiatrist (Foot and Ankle Specialist)",
  "Primary Care Physician (PCP)",
  "Prosthodontist",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist (Lung Doctor)",
  "Radiologist",
  "Rheumatologist",
  "Sleep Medicine Specialist",
  "Sports Medicine Specialist",
  "Surgeon",
  "Therapist / Counselor",
  "Urgent Care Specialist",
  "Urological Surgeon",
  "Urologist",
  "Vascular Surgeon",
  "Endodontist",
  "Periodontist",
];
export { specialitiesOptions };
